version: "1.0"
services:

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_SistemaVentasFactura

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8092:8080"
    container_name: webapp
    depends_on:
      - mysqldb

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    ports:
      - "8091:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: